### ISSUE TITLE
vendor/bundleがアップロードされてしまっている

### ISSUE THREAD

**Issue by nagutabby** [ShiraiChisato/TaskShareApp#1]
# 課題
## GemがGitHubにアップロードされてしまっている
Gemはサイズが大きいため、Gemをアップロードするとgitコマンドの処理が遅くなってしまう
そのため、Gemを格納しているディレクトリはアップロードしない方がいい

# 提案
.gitignoreに/vendor/bundleというコードを追加し、`git rm vendor/bundle`を実行してvendor/bundleをGitの管理対象から除外する

**Comment by ShiraiChisato** [comment]
I see

**Comment by ShiraiChisato** [comment]
解決しました。

**Comment by ShiraiChisato** [comment]
*追記*
".gitignore"に対象ファイルを明記して除外した。
