### ISSUE TITLE
param is missing or the value is empty: project

### ISSUE THREAD

**Issue by ShiraiChisato** [ShiraiChisato/TaskShareApp#10]
Did you mean?
post
commit
controller
action
```
    def posts_params
      params.require(:project).permit(:user, :project, :topic1, :topic2, :topic3, :topic4, :topic5)
    end
```
おそらく:userあたりの書き方がまずい

**Comment by raisa0726** [comment]
# 変更と問題点
```rb
    def posts_params
      params.require(:post).permit(:topic1, :topic2, :topic3, :topic4, :topic5)
    end
```
変更したところ、
unknown attribute 'topic1' for Post.
とエラーが出た

**Comment by waruru** [comment]
Postテーブルのカラム名が`topic1`とかじゃなくて`post1`になってるからだと思うよ!!

**Comment by waruru** [comment]
追記: 
postコントローラのcreateでProjectを検索するときにparams[:id]のように現在していると思うけど、
chromeのデベロッパーツールやサーバーログを見るとわかるけど、パラメータとしてプロジェクトのidが渡されていないです。
![image](https://user-images.githubusercontent.com/68587102/134244185-596ea9db-13be-476c-b0ce-d24f66f47c3e.png)

パラメータとしてプロジェクトのidを渡したいときはhidden_filedなどで以下のようにするといいかも
```erb
<%= form.hidden_field :project_id, value: @project.id %>
```

コントローラで受け取るときは
```ruby
@project = Project.find(params[:post][:project_id])
```
のようにすればいいです

> paramsの受け取りかたについて
formで作成されるパラメータは `form_with` で指定したmodelの中に値が追加されるので、二次元配列のような書き方をしています。
post2の内容を知りたいときは、 `params[:post][:post2]` のように書く

**Comment by raisa0726** [comment]
# 改善策
```rb 
   def posts_params
      params.require(:post).permit(:post1, :post2, :post3, :post4, :post5)
    end
```
に変えた
