### ISSUE TITLE
関連付けされたデータを消せない

### ISSUE THREAD

**Issue by ShiraiChisato** [ShiraiChisato/TaskShareApp#14]
postやユーザーを消すときに、消せない。

**Comment by waruru** [comment]
プロジェクトを消すときに以下のようなエラーが出てる
![image](https://user-images.githubusercontent.com/68587102/134828950-763f2278-54bb-447e-8f59-3b20ba3a75c3.png)

意味としては `外部キーに設定されているからこのデータを削除できない` と言われている。
なので、プロジェクトを削除するときに、関連する` Post` や `Associate` も一緒に削除するようにする必要がある

**Comment by waruru** [comment]
解決方法はProjectのmodelで、関連付けを行っているところに `dependent: :destroy` を追加すればいいです。
これを指定すると親モデルが削除されたときに、子モデルも一緒に削除してくれるようになります。

また、削除するときに`@project.delete` ではなく `@project.destroy` を使う必要があります。

> deleteとdestroyの違いは、関連付けされたデータを一緒に削除するかの違いです。
dependent: :destroyを設定していても、deleteを使うと親データのみしか削除できなくなります。

**Comment by raisa0726** [comment]
# 解決策
controllerを
```rb
  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:notice] = "正常に削除されました"
      redirect_to current_user
    else
      flash[:alert] = "削除できませんでした"
      render :show
    end
  end
```
とした
